### PR TITLE
Branch bug fixes

### LINKED ISSUE #131: Update regex for deadline and for contact number

### PR DESCRIPTION
**Pull request by maxng17**
Bug fixes and update test cases

closes #131

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 1]
```diff
@@ -158,8 +158,13 @@ public static void assertCommandSuccess(Command command, Model actualModel, Comm
         try {
             CommandResult result = command.execute(actualModel);
             assertEquals(expectedCommandResult, result);
+            System.out.println(expectedModel.getFilteredProjectList());
+            System.out.println(actualModel.getFilteredProjectList());
```
Comment (jjtan444) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:162]: Are these output needed?

Comment (maxng17) [reply src/test/java/seedu/address/logic/commands/CommandTestUtil.java]: nope my bad

**Review by jjtan444 — APPROVED** [review]
Good addition of clearer commands. LGTM.
