### PR TITLE
Branch bug fixes

### LINKED ISSUE #151: [PE-D][Tester B] Tag parameter of addproj does not allow for a multiword tag such as 'Not Completed' and returns an incorrect error message
For the 'addproj' command, it does not allow for a multiword tag such as 'Not Completed' or 'In progress' and throws an exception 'Tag names should be alphanumeric'. Please do consider allowing multi-word tags just such as the ones under 'Tasks' or alternatively, please consider modifying the error message to reflect that no more than one word is allowed for a tag.

Input: 
1. addproj pn/CS2100 t/Tiring pb/1000 pd/2022-01-01 t/In progress

Output:

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Vinodjayakumar124/ped#2

### LINKED ISSUE #166: [PE-D][Tester E] Error in editstaff
Warning message indicates that staff index 1 is invalid in project ae sg.

But staff exists in project ae sg

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tinenhao/ped#5

### LINKED ISSUE #170: [PE-D][Tester A] Name of project shown in result display is not the original name
Name of project shown in result display is not the original name

With the following input `editstaff 1 pn/cs2103t tp sp/1234` the result display is shown below.

The project name is shown as "cs2103t tp" (the user input) and not "CS2103T TP" (the original project name). Purely a visual bug since the correct project is identified.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: CFSY/ped#4

### LINKED ISSUE #174: [PE-D][Tester A] filtertask is not an intuitive command name
A user might expect filtertask to filter out marked tasks instead of doing a sort. A suggestion is to rename it to a variant of a sort command.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: CFSY/ped#5

### PR DESCRIPTION
**Pull request by maxng17**
-Update filtertask to sortcomplete to be a more intuitive command name
-Fix bug in error message for edit and delete staff commands 
-Fix bug of original project name not being displayed properly
-Fix bug of tags not displaying properly

closes #174 
closes #170 
closes #166 
closes #151

### CODE REVIEW

File: src/main/java/seedu/address/model/staff/exceptions/DuplicateStaffException.java [hunk 1]
```diff
@@ -2,11 +2,11 @@
 
 /**
  * Signals that the operation will result in duplicate Staffs
```
Comment (jjtan444) [inline src/main/java/seedu/address/model/staff/exceptions/DuplicateStaffException.java:4]: Here should change to "Staff" too?

**Review by Darren12345677 — APPROVED** [review]
LGTM.

File: src/main/java/seedu/address/model/staff/exceptions/DuplicateStaffException.java (hunk 1 above)
Comment (maxng17) [reply src/main/java/seedu/address/model/staff/exceptions/DuplicateStaffException.java]: resolved
